-- AlterTable
ALTER TABLE "dog" ALTER COLUMN "bred_for" SET DATA TYPE TEXT,
ALTER COLUMN "breed_group" SET DATA TYPE TEXT,
ALTER COLUMN "life_span" SET DATA TYPE TEXT,
ALTER COLUMN "name" SET DATA TYPE TEXT,
ALTER COLUMN "origin" SET DATA TYPE TEXT,
ALTER COLUMN "temperament" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "dog_images" ALTER COLUMN "width" SET DATA TYPE TEXT,
ALTER COLUMN "height" SET DATA TYPE TEXT,
ALTER COLUMN "url" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "dog_user" ALTER COLUMN "email" SET DATA TYPE TEXT,
ALTER COLUMN "password" SET DATA TYPE TEXT;
